name: build-script

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.2.2
    -  name: Cache node modules
       uses: actions/cache@v4.2.3
       with:
        path: node_modules
        key: ${{ runner.OS }}-build-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.OS }}-build-${{ env.cache-name }}-
          ${{ runner.OS }}-build-
          ${{ runner.OS }}-
    - uses: actions/setup-node@v4.4.0
      with:
         node-version: '22.15.1'
    - name: use yarn
      run: |
       yarn install
       yarn css
       yarn build