name: cloudflare-pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '18' ]
    name: Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v4.1.5
      -  name: Cache node modules
         uses: actions/cache@v4.0.2
         with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-
      - uses: actions/setup-node@v4.0.2
        with:
          node-version: ${{ matrix.node }}
      - run: yarn install
      - run: yarn css
      - run: yarn build
      - name: Deploy to cloudflare pages
        run: |
          npm install wrangler -g
          wrangler pages deploy public --branch production --project-name=quotesmaker --commit-dirty=true
        env:
            CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
            CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
